### ISSUE TITLE
Thank you! 🙌

### ISSUE THREAD

**Issue by f-liva** [DarkGhostHunter/Laralocker#2]
I wanted to thank you for the wonderful work you've done. Yours is the ONLY clean and functional, and very intelligent, solution for the management of race conditions in Laravel.

I didn't find a way to contact you but I wanted to thank you from me and my whole team! ❤

Thanks from https://vivi.city/

**Comment by DarkGhostHunter** [comment]
It warms my heart. Thanks.

As a guy at most 1/8 italian, I won't be mad if you send me a pizza.

**Comment by f-liva** [comment]
Absolutely, it has already been confirmed by the team!

Please leave me an email, we want to send you a donation ✌

**Comment by DarkGhostHunter** [comment]
[Here is](https://github.com/DarkGhostHunter/Laralocker/blob/master/composer.json#L14) 🤫
